language: python
python:
  - "2.7"
  - "3.5"
install:
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script: nose
