language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
  - osx
sudo: required
install:
  - ./.travis/install.sh
  - pip install .
# command to run tests
script:
  - nosetests --with-coverage
after_success:
  - codecov
  - coveralls
